// 打字模块的内置词库。条目内容使用 ASCII 标点，保证物理键盘可直接输入。
export type CategoryKind = "word" | "sentence";

export interface BuiltinCategory {
  id: string;
  name: string;
  kind: CategoryKind;
  entries: readonly string[];
}

export const BUILTIN_CATEGORIES: readonly BuiltinCategory[] = [
  {
    id: "common-words",
    name: "常用词汇",
    kind: "word",
    entries: [
      "ability", "about", "across", "action", "against", "almost", "always", "animal",
      "answer", "around", "become", "before", "believe", "between", "bring", "build",
      "carry", "change", "choose", "city", "close", "common", "could", "country",
      "course", "create", "develop", "different", "during", "early", "earth", "enough",
      "every", "example", "family", "follow", "friend", "general", "great", "group",
      "happen", "important", "interest", "keep", "large", "learn", "letter", "little",
      "look", "mountain", "move", "never", "number", "often", "people", "place",
      "point", "question", "really", "school", "second", "small", "something", "still",
      "story", "study", "system", "thing", "think", "thought", "together", "under",
      "until", "water", "while", "world", "write", "young",
    ],
  },
  {
    id: "coding-words",
    name: "编程词汇",
    kind: "word",
    entries: [
      "async", "await", "boolean", "branch", "buffer", "cache", "class", "commit",
      "compile", "const", "context", "debug", "deploy", "domain", "enum", "error",
      "export", "fetch", "field", "function", "generic", "import", "index", "inject",
      "input", "kernel", "lambda", "library", "lint", "module", "mutex", "node",
      "object", "package", "param", "parser", "pointer", "process", "query", "queue",
      "react", "render", "route", "schema", "script", "server", "socket", "static",
      "stream", "string", "struct", "syntax", "thread", "token", "tuple", "type",
      "update", "value", "variable", "vector", "worker", "yield",
    ],
  },
  {
    id: "daily-sentences",
    name: "日常英语",
    kind: "sentence",
    entries: [
      "The early bird catches the worm.",
      "Could you do me a favor?",
      "Practice makes perfect.",
      "Let's take a break and have some coffee.",
      "It has been a long day.",
      "What do you usually do on weekends?",
      "I will keep that in mind.",
      "That sounds like a great idea.",
      "Better late than never.",
      "Could you say that again, please?",
      "I am looking forward to seeing you.",
      "Let's get straight to the point.",
      "It depends on the weather.",
      "Time flies when you are having fun.",
      "Don't worry, everything will be fine.",
      "Can you give me a hand with this?",
      "I couldn't agree with you more.",
      "That is easier said than done.",
      "Keep in touch and take care.",
      "Sorry, I didn't catch your name.",
      "We are running out of time.",
      "You can say that again.",
      "Let me think it over.",
      "It is not a big deal.",
      "Long time no see.",
      "How is it going lately?",
      "Make yourself at home.",
    ],
  },
  {
    id: "quote-sentences",
    name: "名言佳句",
    kind: "sentence",
    entries: [
      "Stay hungry, stay foolish.",
      "Knowledge is power.",
      "Actions speak louder than words.",
      "Where there is a will, there is a way.",
      "The only limit is your imagination.",
      "Simplicity is the ultimate sophistication.",
      "Well begun is half done.",
      "No pain, no gain.",
      "Honesty is the best policy.",
      "Rome was not built in a day.",
      "Fortune favors the bold.",
      "To be or not to be, that is the question.",
      "All that glitters is not gold.",
      "Every cloud has a silver lining.",
      "A journey of a thousand miles begins with a single step.",
      "Failure is the mother of success.",
      "Do not go gentle into that good night.",
      "In the middle of difficulty lies opportunity.",
      "Imagination is more important than knowledge.",
      "Nothing ventured, nothing gained.",
      "Slow and steady wins the race.",
      "It always seems impossible until it is done.",
      "Quality is not an act, it is a habit.",
      "The best way out is always through.",
    ],
  },
];
